name: Terraform Workflow

on:
  push:
    branches: [ feature/* ]
    tags:
      - 'destroy-*'   # Executa destroy quando uma tag que começa com 'destroy-' é criada
  pull_request:
  workflow_dispatch:    # Permite execução manual

jobs:
  terraform:
    name: Terraform Init, Plan, Apply e Destroy
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}  # Define a região da AWS, se necessário

    steps:
      # Passo 1: Checkout do código
      - name: Checkout repository
        uses: actions/checkout@v3

      # Passo 2: Configurar o Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0  # Substitua pela versão desejada

      # Passo 3: Configurar Credenciais da AWS
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Passo 4: Inicializar o Terraform
      - name: Terraform Init
        run: terraform init

      # Passo 5: Validar a configuração do Terraform
      - name: Terraform Validate
        run: terraform validate

      # Passo 6: Executar o Terraform Plan
      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan

      # Passo 8: Aplicar as mudanças
      - name: Terraform Apply
        if: github.ref == 'refs/heads/feature/apply' && github.event_name == 'push'
        run: terraform apply -auto-approve tfplan

      # Passo 9: Destruir a infraestrutura
      - name: Terraform Destroy
        if: startsWith(github.ref, 'refs/tags/destroy') || github.event_name == 'workflow_dispatch'
        run: terraform destroy -auto-approve